#!/bin/bash

source /usr/bin/_colours

# clear log files
echo -ne "" > /var/log/build.log
echo -ne "" > /var/log/webpack.log
echo -ne "" > /var/log/express.log

# clear screen
clear

echo -e "${BGreen}Viewing application log,${Color_Off} hit ctrl+c to end and return to the command line"
echo ""

tail -f -s 0.1 /var/log/express.log /var/log/webpack.log /var/log/build.log
